# Site settings
title: Gaurav Singh
email: gs.cyber.red@gmail.com
description: "Cybersecurity Engineer | VAPT Specialist | Information Security Engineer"
tagline: "VAPT | Cyber Security Engineer | Penetration Testing"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title.html

# GitHub Pages specific settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# GitHub Pages defaults
defaults:
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "_projects"
      type: "projects"
    values:
      layout: "project"

# Social media usernames
github_username: GauravSingh-CyberSecurity
linkedin_username: gaurav-singh-cybersecurity
twitter_username: your-twitter-username

# Variables
baseurl: ""
url: "https://gauravsingh-cybersecurity.github.io"

# Collections
collections:
  pages:
    output: true
    permalink: /:name/
  projects:
    output: true
    permalink: /projects/:name/
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title.html

# Navigation
navigation:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Projects
    url: /projects/
  - title: Blog
    url: /blog/
  - title: Research
    url: /research/
  - title: CV
    url: /cv/
  - title: Contact
    url: /contact/

# Include and exclude
include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .git
  - .gitignore

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Site author
author:
  name: Gaurav Singh
  bio: "Cybersecurity Engineer specializing in Vulnerability Assessment and Penetration Testing (VAPT), with hands-on experience in exploiting OWASP Top 10, Web, API, Android misconfigurations, and business logic flaws across enterprise applications."
  location: "Nagpur, Maharashtra"
  phone: "+91 9765809266"
  skills:
    - "Web/App Security (Burp Suite Pro, OWASP ZAP, Nmap)"
    - "Exploitation (SQLMap, Metasploit, Nikto, John the Ripper)"
    - "Reconnaissance (FFUF, Subfinder, Gobuster, Amass)"
    - "Scripting (Python, JavaScript, Bash)"
    - "Security Standards (OWASP Top 10, MITRE ATT&CK, CVE)"
    - "Attack Vectors (SQLi, XSS, SSRF, RCE, IDOR, Auth Bypass)"
